services:
  mongodb:
    image: mongo:latest
    container_name: agro_mongo_dev
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=agroadmin
      - MONGO_INITDB_ROOT_PASSWORD=agro123
    env_file:
      - ./envs/.env.dev
    networks:
      - dev-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  nest-backend:
    build:
      context: ..
      dockerfile: services/backend/Dockerfile.dev
    container_name: agro_backend_dev
    ports:
      - "3001:3001"
    env_file:
      - ./envs/.env.dev
    volumes:
      - ../services/backend/src:/app/services/backend/src
      - ../services/backend/logs:/app/services/backend/logs
    networks:
      - dev-net
    depends_on:
      mongodb:
        condition: service_healthy
  backend1:
    build: ../backend
    container_name: agro_backend1_dev
    env_file:
      - ./envs/.env.dev
    volumes:
      - ../backend/logs:/app/logs
      - ../backend:/app
      - /app/node_modules
    networks:
      - dev-net
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
  backend2:
    build: ../backend
    container_name: agro_backend2_dev
    env_file:
      - ./envs/.env.dev
    volumes:
      - ../backend/logs:/app/logs
      - ../backend:/app
      - /app/node_modules
    networks:
      - dev-net
    depends_on:
      - mongodb
    command: ["npm", "run", "dev"]
  frontend:
    build: ../frontend
    container_name: agro_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend1
      - backend2
    command: ["npm", "run", "dev"]
  nginx:
    image: nginx:latest
    container_name: nginx_dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - dev-net
    depends_on:
      - frontend
      - backend1
      - backend2
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/loki-config.yaml
  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./logs/nginx:/logs/nginx:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.1.0
    ports:
      - "9113:9113"
    command:
      - "--nginx.scrape-uri=http://nginx/status"
volumes:
  data:
  logs:
  grafana_data:
networks:
  dev-net:
    driver: bridge
